#PROD environment

app:
  message: This is the property file fo the ${spring.application.name} specific to PROD Environment

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: <MYSQL_URL>
    username: <USERNAME>
    password: <PASSWORD>
