#DEV environment

app:
  message: This is the property file fo the ${spring.application.name} specific to DEV Environment

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
